name: Build with ESP-IDF

on: 
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [esp32, esp32s2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
   
      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1
          target: ${{ matrix.platform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: build/esp32-evse.bin

      - name: Get release info
        id: get_release_info
        run: |
          echo ::set-output name=file_name::${REPOSITORY_NAME##*/}-${TAG_REF_NAME##*/v} # RepositoryName-v1.0.0
          value=`cat release_url/release_url.txt`
          echo ::set-output name=upload_url::$value
        env:
          TAG_REF_NAME: ${{ github.ref }}
          REPOSITORY_NAME: ${{ github.repository }}
          
      - name: Upload release assets
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./build/esp32-evse.bin
          asset_name: '${{ matrix.platform }}-evse.bin'
          asset_content_type: application/octet-stream