name: Build with ESP-IDF

on: 
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [esp32, esp32s2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
   
      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1
          target: ${{ matrix.platform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware-${{ matrix.platform }}
          path: build/esp32-evse.bin
