name: Build with ESP-IDF

on: 
  push:
    branches: 
      - master
  release:
    types:
      - created  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for ESP32
        uses: actions/checkout@v3
        with:
          submodules: true
          path: esp32

      - name: Checkout for ESP32-S2
        uses: actions/checkout@v3
        with:
          submodules: true
          path: esp32s2
   
      - name: Build ESP32
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.3
          target: esp32
          path: esp32
     
      - name: Build ESP32-S2
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.3
          target: esp32s2
          path: esp32s2

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              name: 'esp32-evse.bin',
              data: fs.readFileSync('./build/esp32-evse.bin')
            });
